apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-hostpath
  annotations:
    policies.kyverno.io/title: Disallow hostPath Volumes
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: high
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-hostpath
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaces:
                - boutique
                - default
      validate:
        message: "hostPath volumes are not allowed — they expose the node filesystem."
        pattern:
          spec:
            =(volumes):
              - X(hostPath): "null"
